### ISSUE TITLE
Update URLs

### ISSUE THREAD

**Issue by CoreyWycliffe** [Vantiv/litle-sdk-for-php#39]
Are you going to update your urls for the August 31st deadline?

https://www.vantiv.com/content/dam/vantiv/merchants-partners/docs/ecommerce-domains-faq-june-2017.pdf

**Comment by sumityadav** [comment]
It would also be good if we can remove the URL's from Setup.php file that are not relevant.

**Comment by brianarnold789** [comment]
Both of these items will be addressed in new release by the end of the month.

**Comment by brianarnold789** [comment]
URLs are now updated, We will update the Sandbox URL when we have everything in place to ensure uninterrupted access.

**Comment by CoreyWycliffe** [comment]
Does this have to be updated too?
https://github.com/Vantiv/litle-sdk-for-php/blob/11.0/litle/sdk/UrlMapper.php

**Comment by brianarnold789** [comment]
Correct, missed adding this file to the commit. Should be all set now.
